import { useEffect, useState } from "react";
import { LogOut, Settings2 } from "lucide-react";
import { signOut } from "firebase/auth";
import { auth } from "../../lib/firebase";
import type { AppALanguage, AppAPreferences } from "../types";
import { isValidTimeZone } from "../settings/preferences";

const COPY = {
  en: { eyebrow: "Your preferences", title: "Settings", intro: "Control how App A behaves on this device.", language: "Language", theme: "Appearance", system: "System", light: "Light", dark: "Dark", zone: "Time zone", zoneHelp: "Used for daily plans and routine dates.", focus: "Default focus session", ai: "AI daily planning", aiHelp: "Turning this off prevents new AI daily plans; saved content remains available.", logout: "Sign out", invalidZone: "Enter a valid IANA time zone, for example Europe/Belgrade." },
  sr: { eyebrow: "Vaše preference", title: "Podešavanja", intro: "Kontrolišite kako se App A ponaša na ovom uređaju.", language: "Jezik", theme: "Izgled", system: "Sistemski", light: "Svetli", dark: "Tamni", zone: "Vremenska zona", zoneHelp: "Koristi se za dnevne planove i datume rutina.", focus: "Podrazumevana fokus sesija", ai: "AI dnevno planiranje", aiHelp: "Isključivanje sprečava nove AI dnevne planove; sačuvani sadržaj ostaje dostupan.", logout: "Odjavi se", invalidZone: "Unesite validnu IANA vremensku zonu, na primer Europe/Belgrade." },
  tr: { eyebrow: "Tercihleriniz", title: "Ayarlar", intro: "App A'nın bu cihazda nasıl davrandığını kontrol edin.", language: "Dil", theme: "Görünüm", system: "Sistem", light: "Açık", dark: "Koyu", zone: "Saat dilimi", zoneHelp: "Günlük planlar ve rutin tarihleri için kullanılır.", focus: "Varsayılan odak oturumu", ai: "AI günlük planlama", aiHelp: "Kapatıldığında yeni AI günlük planları durur; kayıtlı içerik kalır.", logout: "Çıkış yap", invalidZone: "Europe/Belgrade gibi geçerli bir IANA saat dilimi girin." },
} as const;

export default function SettingsScreen({ language, preferences, onChange }: { language: AppALanguage; preferences: AppAPreferences; onChange: (next: AppAPreferences) => void }) {
  const t = COPY[language];
  const [zoneDraft, setZoneDraft] = useState(preferences.timeZone);
  useEffect(() => setZoneDraft(preferences.timeZone), [preferences.timeZone]);
  const update = <K extends keyof AppAPreferences>(key: K, value: AppAPreferences[K]) => onChange({ ...preferences, [key]: value });
  return <div className="mx-auto w-full max-w-[680px] px-5 pb-8 sm:px-6"><header className="mb-7"><p className="app-a-eyebrow">{t.eyebrow}</p><h1 className="app-a-page-title">{t.title}</h1><p className="app-a-page-intro">{t.intro}</p></header><div className="app-a-surface divide-y divide-black/5 overflow-hidden dark:divide-white/10">
    <section className="p-5"><label className="text-[15px] font-semibold">{t.language}</label><select value={preferences.language} onChange={(event) => update("language", event.target.value as AppALanguage)} className="app-a-field app-a-focus-ring mt-2 w-full p-3"><option value="en">English</option><option value="sr">Srpski</option><option value="tr">Türkçe</option></select></section>
    <section className="p-5"><p className="text-[15px] font-semibold">{t.theme}</p><div className="mt-2 grid grid-cols-3 gap-2">{(["system", "light", "dark"] as const).map((theme) => <button key={theme} type="button" onClick={() => update("theme", theme)} className={`app-a-focus-ring min-h-11 rounded-xl border text-[13px] font-semibold ${preferences.theme === theme ? "border-[#0071E3] bg-[#0071E3] text-white" : "border-black/10 dark:border-white/15"}`}>{t[theme]}</button>)}</div></section>
    <section className="p-5"><label className="text-[15px] font-semibold" htmlFor="app-a-timezone">{t.zone}</label><input id="app-a-timezone" value={zoneDraft} onChange={(event) => setZoneDraft(event.target.value)} onBlur={() => { if (isValidTimeZone(zoneDraft)) update("timeZone", zoneDraft); }} aria-invalid={!isValidTimeZone(zoneDraft)} className="app-a-field app-a-focus-ring mt-2 w-full p-3" /><p className="mt-1 text-[12px] text-[#6E6E73] dark:text-[#AEAEB2]">{isValidTimeZone(zoneDraft) ? t.zoneHelp : t.invalidZone}</p></section>
    <section className="p-5"><label className="text-[15px] font-semibold">{t.focus}</label><select value={preferences.defaultFocusMinutes} onChange={(event) => update("defaultFocusMinutes", Number(event.target.value) as AppAPreferences["defaultFocusMinutes"])} className="app-a-field app-a-focus-ring mt-2 w-full p-3">{[15,25,45,60].map((value) => <option key={value} value={value}>{value} min</option>)}</select></section>
    <section className="flex items-start justify-between gap-4 p-5"><div><p className="text-[15px] font-semibold">{t.ai}</p><p className="mt-1 text-[12px] leading-relaxed text-[#6E6E73] dark:text-[#AEAEB2]">{t.aiHelp}</p></div><button type="button" role="switch" aria-checked={preferences.aiSuggestionsEnabled} onClick={() => update("aiSuggestionsEnabled", !preferences.aiSuggestionsEnabled)} className={`app-a-focus-ring relative mt-1 h-8 w-14 shrink-0 rounded-full ${preferences.aiSuggestionsEnabled ? "bg-[#34C759]" : "bg-black/15 dark:bg-white/20"}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white shadow transition-transform ${preferences.aiSuggestionsEnabled ? "translate-x-6" : "translate-x-1"}`} /></button></section>
  </div><button type="button" onClick={() => void signOut(auth)} className="app-a-secondary-button app-a-focus-ring mt-5 w-full gap-2"><LogOut className="h-4 w-4" />{t.logout}</button><div className="mt-4 flex justify-center text-[#8E8E93]"><Settings2 className="h-4 w-4" /></div></div>;
}
