import { useEffect, useMemo, useState } from "react";
import { Archive, Check, ChevronDown, ChevronRight, Compass, Lightbulb, Plus, RotateCcw, Sparkles, Trash2, X } from "lucide-react";
import type { SavedVisionStrategy } from "../../shared/domain/vision";
import { deleteVisionStrategy, loadCurrentVisionId, loadVisionLibrary, setCurrentVisionId, setVisionStrategyArchived, visionIdeaFingerprint } from "../../shared/persistence/vision";
import PlanHistoryState from "../components/PlanHistoryState";
import VoiceInputButton from "../components/voice/VoiceInputButton";
import VisionStrategyBuilder from "../components/vision/VisionStrategyBuilder";
import { readSessionDraft, writeSessionDraft } from "../persistence/sessionDraft";
import type { AppALanguage } from "../types";
import { getVisionItems } from "./planHistory";
import { useAppAPlanHistory } from "./useAppAPlanHistory";

const COPY = {
  en: { eyebrow:"Long-term direction", title:"Vision", intro:"Keep several directions, develop one at a time, and choose which one guides Today.", guide:"How Vision works", guideIntro:"Vision is for meaningful directions that take more than one day — not today’s errands or notes.", guideCapture:"Add a direction in your own words. A timeframe is optional; the app can suggest a realistic one.", guideDevelop:"Develop it into milestones and small next steps. You can keep several visions in your library.", guideFocus:"Choose one current focus. It guides Today; other visions may occasionally offer one optional step, but nothing enters your plan without your confirmation.", placeholder:"Describe a direction or goal…", add:"New vision", active:"Active", archived:"Archived", empty:"No visions in this view.", current:"Current focus", currentHelp:"Only this vision guides the primary suggestions in Today.", noCurrent:"Choose a current focus", noCurrentHelp:"Select one active vision to guide Today. The others remain available without taking over your plan.", openCurrent:"Open focus", makeCurrent:"Set as current focus", library:"Your visions", draft:"Not developed yet", archive:"Archive", restore:"Restore", remove:"Delete", confirm:"Permanently delete this vision?", cancel:"Cancel", error:"The vision could not be updated. Try again.", choose:"Choose a vision from the list or add a new one.", original:"Original entry" },
  sr: { eyebrow:"Dugoročni pravac", title:"Vizija", intro:"Sačuvajte više pravaca, razrađujte jedan po jedan i izaberite koji vodi današnje predloge.", guide:"Kako radi Vizija", guideIntro:"Vizija služi za važne pravce koji traju duže od jednog dana — ne za današnje obaveze ili beleške.", guideCapture:"Unesite pravac svojim rečima. Rok je opcion; aplikacija može predložiti realan vremenski okvir.", guideDevelop:"Razradite ga u etape i male sledeće korake. Možete sačuvati više vizija u biblioteci.", guideFocus:"Izaberite jedan trenutni fokus. On vodi Danas; druge vizije mogu povremeno ponuditi jedan opcioni korak, ali ništa ne ulazi u plan bez vaše potvrde.", placeholder:"Opišite pravac ili cilj…", add:"Nova vizija", active:"Aktivne", archived:"Arhivirane", empty:"Nema vizija u ovom prikazu.", current:"Trenutni fokus", currentHelp:"Samo ova vizija vodi glavne predloge u odeljku Danas.", noCurrent:"Izaberite trenutni fokus", noCurrentHelp:"Izaberite jednu aktivnu viziju koja vodi Danas. Ostale ostaju dostupne bez preuzimanja plana.", openCurrent:"Otvori fokus", makeCurrent:"Postavi kao trenutni fokus", library:"Vaše vizije", draft:"Još nije razrađena", archive:"Arhiviraj", restore:"Vrati", remove:"Obriši", confirm:"Trajno obrisati ovu viziju?", cancel:"Otkaži", error:"Vizija nije mogla da se izmeni. Pokušajte ponovo.", choose:"Izaberite viziju sa liste ili dodajte novu.", original:"Originalni unos" },
  tr: { eyebrow:"Uzun vadeli yön", title:"Vizyon", intro:"Birden fazla yönü saklayın, her seferinde birini geliştirin ve Bugün'ü hangisinin yönlendireceğini seçin.", guide:"Vizyon nasıl çalışır?", guideIntro:"Vizyon, bir günden uzun süren anlamlı yönler içindir; bugünün işleri veya notları için değildir.", guideCapture:"Yönünüzü kendi sözlerinizle ekleyin. Süre isteğe bağlıdır; uygulama gerçekçi bir zaman aralığı önerebilir.", guideDevelop:"Bunu aşamalara ve küçük sonraki adımlara dönüştürün. Kitaplığınızda birden fazla vizyon tutabilirsiniz.", guideFocus:"Bir mevcut odak seçin. Bugün'ü o yönlendirir; diğer vizyonlar bazen isteğe bağlı tek bir adım sunabilir, ancak onayınız olmadan hiçbir şey planınıza girmez.", placeholder:"Bir yön veya hedef açıklayın…", add:"Yeni vizyon", active:"Aktif", archived:"Arşiv", empty:"Bu görünümde vizyon yok.", current:"Mevcut odak", currentHelp:"Bugün bölümündeki ana önerileri yalnızca bu vizyon yönlendirir.", noCurrent:"Mevcut odağı seçin", noCurrentHelp:"Bugün'ü yönlendirecek bir aktif vizyon seçin. Diğerleri planınızı devralmadan kullanılabilir kalır.", openCurrent:"Odağı aç", makeCurrent:"Mevcut odak yap", library:"Vizyonlarınız", draft:"Henüz geliştirilmedi", archive:"Arşivle", restore:"Geri yükle", remove:"Sil", confirm:"Bu vizyon kalıcı olarak silinsin mi?", cancel:"İptal", error:"Vizyon güncellenemedi. Tekrar deneyin.", choose:"Listeden bir vizyon seçin veya yenisini ekleyin.", original:"Orijinal giriş" },
} as const;
const VISION_SIGN_IN_COPY = {
  en: { title: "Your visions stay private", text: "Sign in to save your Vision library, current focus, and progress across days." },
  sr: { title: "Vaše vizije ostaju privatne", text: "Prijavite se da biste sačuvali biblioteku Vizija, trenutni fokus i napredak kroz dane." },
  tr: { title: "Vizyonlarınız gizli kalır", text: "Vizyon kitaplığınızı, mevcut odağınızı ve günler içindeki ilerlemenizi kaydetmek için giriş yapın." },
} as const;
const VISION_GUIDE_KEY = "app_a_vision_guide_seen_v1";
const shouldOpenVisionGuide = () => { try { return localStorage.getItem(VISION_GUIDE_KEY) !== "seen"; } catch { return true; } };
type Draft = { draftIdea:string; manualIdeas:string[] };
const validDraft = (value:unknown):value is Draft => { const v=value as Draft; return !!v && typeof v.draftIdea==="string" && v.draftIdea.length<=4000 && Array.isArray(v.manualIdeas) && v.manualIdeas.every(x=>typeof x==="string"&&x.length<=4000); };
const compactVisionTitle = (value:string) => { const clean=value.replace(/\s+/g," ").trim(); const sentence=clean.match(/^.*?[.!?](?:\s|$)/)?.[0]?.trim()||clean; return sentence.length>88?`${sentence.slice(0,85).trimEnd()}…`:sentence; };

export default function VisionScreen({ language }: { language:AppALanguage }) {
  const history=useAppAPlanHistory(), t=COPY[language], key=`${history.user?.uid||"guest"}:vision:screen`;
  const [initial]=useState(()=>readSessionDraft<Draft>(key,{draftIdea:"",manualIdeas:[]},validDraft));
  const [draftIdea,setDraftIdea]=useState(initial.draftIdea), [manualIdeas,setManualIdeas]=useState(initial.manualIdeas);
  const [saved,setSaved]=useState<SavedVisionStrategy[]>([]), [view,setView]=useState<"active"|"archived">("active");
  const [deletedFingerprints,setDeletedFingerprints]=useState<string[]>([]), [suppressedIdeas,setSuppressedIdeas]=useState<string[]>([]);
  const [selected,setSelected]=useState<string|null>(null), [focusId,setFocusId]=useState<string|null>(null);
  const [busy,setBusy]=useState<string|null>(null), [confirm,setConfirm]=useState<string|null>(null), [error,setError]=useState(false);
  const [guideOpen,setGuideOpen]=useState(shouldOpenVisionGuide);
  const toggleGuide=()=>setGuideOpen(open=>{const next=!open;if(!next){try{localStorage.setItem(VISION_GUIDE_KEY,"seen")}catch{/* storage can be unavailable */}}return next});
  const renderGuide=()=> <section className="app-a-surface mb-4 overflow-hidden" aria-labelledby="vision-guide-heading"><button type="button" onClick={toggleGuide} aria-expanded={guideOpen} className="app-a-focus-ring flex min-h-12 w-full items-center justify-between gap-3 px-4 py-3 text-left"><span id="vision-guide-heading" className="inline-flex items-center gap-2 text-[14px] font-semibold"><Compass className="h-4 w-4 text-[#AF52DE]"/>{t.guide}</span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${guideOpen?"rotate-180":""}`}/></button>{guideOpen?<div className="grid gap-3 border-t p-4 sm:grid-cols-3" style={{borderColor:"var(--app-a-border)"}}><div><p className="text-[13px] font-semibold">1</p><p className="mt-1 text-[13px] leading-relaxed" style={{color:"var(--app-a-text-secondary)"}}>{t.guideIntro} {t.guideCapture}</p></div><div><p className="text-[13px] font-semibold">2</p><p className="mt-1 text-[13px] leading-relaxed" style={{color:"var(--app-a-text-secondary)"}}>{t.guideDevelop}</p></div><div><p className="text-[13px] font-semibold">3</p><p className="mt-1 text-[13px] leading-relaxed" style={{color:"var(--app-a-text-secondary)"}}>{t.guideFocus}</p></div></div>:null}</section>;
  useEffect(()=>writeSessionDraft(key,{draftIdea,manualIdeas}),[draftIdea,key,manualIdeas]);
  useEffect(()=>{ if(!history.user)return; let live=true; Promise.all([loadVisionLibrary(history.user.uid),loadCurrentVisionId(history.user.uid)]).then(([lib,current])=>{if(!live)return; setSaved(lib.strategies);setDeletedFingerprints(lib.deletedFingerprints); const active=lib.strategies.filter(x=>x.status!=="archived"); const valid=active.some(x=>x.id===current)?current:null; setFocusId(valid); setSelected(active[0]?.id||lib.strategies[0]?.id||null); if(!valid&&active.length===1)void setCurrentVisionId(history.user!.uid,active[0].id).then(()=>setFocusId(active[0].id));}).catch(()=>setError(true)); return()=>{live=false};},[history.user]);
  const [historyIdeas,setHistoryIdeas]=useState<Array<{idea:string;fingerprint:string}>>([]);
  useEffect(()=>{let live=true;const ideas=[...new Set(getVisionItems(history.plans).map(({item})=>item.suggestedAction||item.originalText))];void Promise.all(ideas.map(async idea=>({idea,fingerprint:await visionIdeaFingerprint(idea)}))).then(result=>{if(live)setHistoryIdeas(result)});return()=>{live=false}},[history.plans]);
  const imported=useMemo(()=>historyIdeas.filter(({idea,fingerprint})=>!deletedFingerprints.includes(fingerprint)&&!suppressedIdeas.includes(idea)&&!saved.some(x=>x.idea===idea)).map(({idea})=>idea),[deletedFingerprints,historyIdeas,saved,suppressedIdeas]);
  useEffect(()=>setManualIdeas(current=>[...new Set([...current,...imported])]),[imported]);
  if(!history.authReady||history.loading)return <PlanHistoryState language={language} state="loading"/>;
  if(history.error)return <PlanHistoryState language={language} state="error" onSignIn={history.retry}/>;
  if(!history.user)return <div className="mx-auto w-full max-w-[980px] px-4 pb-10 sm:px-6"><header className="mb-6"><p className="app-a-eyebrow">{t.eyebrow}</p><h1 className="app-a-page-title">{t.title}</h1><p className="app-a-page-intro max-w-[680px]">{t.intro}</p></header>{renderGuide()}<PlanHistoryState language={language} state="sign_in" onSignIn={()=>void history.signIn()} signInTitle={VISION_SIGN_IN_COPY[language].title} signInText={VISION_SIGN_IN_COPY[language].text}/></div>;
  const activeSaved=saved.filter(item=>item.status!=="archived"), currentVision=activeSaved.find(item=>item.id===focusId)||null;
  const drafts=view==="active"?manualIdeas.filter(idea=>!suppressedIdeas.includes(idea)&&!deletedFingerprints.includes(historyIdeas.find(entry=>entry.idea===idea)?.fingerprint||"")&&!saved.some(x=>x.idea===idea)):[], shown=saved.filter(x=>view==="archived"?x.status==="archived":x.status!=="archived");
  const selectedSaved=saved.find(x=>x.id===selected), selectedDraft=selected?.startsWith("draft:")?selected.slice(6):null;
  const focus=async(id:string)=>{setBusy(id);try{await setCurrentVisionId(history.user!.uid,id);setFocusId(id);window.dispatchEvent(new Event("app-a-vision-candidates-changed"));}catch{setError(true)}finally{setBusy(null)}};
  const archive=async(item:SavedVisionStrategy)=>{setBusy(item.id);try{const next=await setVisionStrategyArchived(history.user!.uid,item,item.status!=="archived");setSaved(all=>all.map(x=>x.id===next.id?next:x));if(next.status==="archived"&&focusId===next.id){await setCurrentVisionId(history.user!.uid,null);setFocusId(null)}setSelected(null);window.dispatchEvent(new Event("app-a-vision-candidates-changed"));}catch{setError(true)}finally{setBusy(null)}};
  const remove=async(item:SavedVisionStrategy)=>{setBusy(item.id);try{await deleteVisionStrategy(history.user!.uid,item.id);const fingerprint=await visionIdeaFingerprint(item.idea);setDeletedFingerprints(all=>[...new Set([...all,fingerprint])]);setSuppressedIdeas(all=>[...new Set([...all,item.idea])]);setManualIdeas(all=>all.filter(idea=>idea!==item.idea));if(focusId===item.id){await setCurrentVisionId(history.user!.uid,null);setFocusId(null)}setSaved(all=>all.filter(x=>x.id!==item.id));setSelected(null);setConfirm(null);}catch{setError(true)}finally{setBusy(null)}};
  const add=()=>{const idea=draftIdea.trim();if(idea.length<3)return;setManualIdeas(all=>[idea,...all.filter(x=>x!==idea)]);setSelected(`draft:${idea}`);setView("active");setDraftIdea("")};
  return <div className="mx-auto w-full max-w-[980px] px-4 pb-10 sm:px-6">
    <header className="mb-6"><p className="app-a-eyebrow">{t.eyebrow}</p><h1 className="app-a-page-title">{t.title}</h1><p className="app-a-page-intro max-w-[680px]">{t.intro}</p></header>
    {renderGuide()}
    <form className="app-a-surface mb-4 p-4" onSubmit={e=>{e.preventDefault();add()}}><div className="relative"><textarea value={draftIdea} onChange={e=>setDraftIdea(e.target.value)} maxLength={4000} rows={2} placeholder={t.placeholder} className="app-a-field app-a-focus-ring w-full resize-y p-3 pr-14 text-[15px]"/><div className="absolute right-2 top-2"><VoiceInputButton language={language} value={draftIdea} onChange={setDraftIdea} maxLength={4000}/></div></div><button disabled={draftIdea.trim().length<3} className="app-a-primary-button mt-3 gap-2 px-4"><Plus className="h-4 w-4"/>{t.add}</button></form>
    <div className="mb-4 flex gap-2"><button onClick={()=>{setView("active");setSelected(null)}} className={view==="active"?"app-a-primary-button px-4":"app-a-secondary-button px-4"}>{t.active}</button><button onClick={()=>{setView("archived");setSelected(null)}} className={view==="archived"?"app-a-primary-button px-4":"app-a-secondary-button px-4"}>{t.archived}</button></div>
    {view==="active"&&currentVision?<section className="mb-4 rounded-2xl border border-[#34C759]/35 bg-[#34C759]/[0.07] p-4 sm:p-5" aria-labelledby="current-vision-heading"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><p className="flex items-center gap-1.5 text-[12px] font-semibold uppercase tracking-[0.07em] text-[#248A3D]"><Check className="h-4 w-4"/>{t.current}</p><h2 id="current-vision-heading" className="mt-1 break-words text-[18px] font-semibold">{compactVisionTitle(currentVision.planningContext?.acceptedGoal||currentVision.idea)}</h2><p className="mt-1 text-[13px]" style={{color:"var(--app-a-text-secondary)"}}>{t.currentHelp}</p></div><button type="button" onClick={()=>setSelected(currentVision.id)} className="app-a-secondary-button shrink-0 px-4 text-[13px]">{t.openCurrent}<ChevronRight className="h-4 w-4"/></button></div></section>:null}
    {view==="active"&&!currentVision&&activeSaved.length>1?<section className="app-a-panel-warning mb-4"><h2 className="text-[15px] font-semibold">{t.noCurrent}</h2><p className="mt-1 text-[13px] leading-relaxed">{t.noCurrentHelp}</p></section>:null}
    {error?<p role="alert" className="app-a-panel-danger mb-3 text-[13px]">{t.error}</p>:null}
    <div className="grid items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)]"><section className="app-a-surface overflow-hidden"><h2 className="border-b px-4 py-3 text-[14px] font-semibold" style={{borderColor:"var(--app-a-border)"}}>{t.library}</h2>{shown.length+drafts.length===0?<div className="flex min-h-[140px] flex-col items-center justify-center gap-2 p-6 text-center"><Lightbulb className="h-5 w-5 text-[#AF52DE]"/><p className="text-[13px]">{t.empty}</p></div>:<div>
      {shown.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={`app-a-focus-ring flex w-full items-start gap-3 border-b p-4 text-left ${selected===item.id?"bg-[#AF52DE]/10":""}`} style={{borderColor:"var(--app-a-border)"}}><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#AF52DE]"/><span className="min-w-0 flex-1"><span className="block break-words text-[14px] font-semibold">{compactVisionTitle(item.planningContext?.acceptedGoal||item.idea)}</span><span className="mt-1 block text-[11px]" style={{color:"var(--app-a-text-secondary)"}}>{focusId===item.id?t.current:item.planningContext?.timeframe||""}</span></span><ChevronRight className="mt-1 h-4 w-4 opacity-40"/></button>)}
      {drafts.map(idea=><button key={idea} onClick={()=>setSelected(`draft:${idea}`)} className={`app-a-focus-ring flex w-full items-start gap-3 border-b p-4 text-left ${selected===`draft:${idea}`?"bg-[#AF52DE]/10":""}`}><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#AF52DE]"/><span className="min-w-0 flex-1"><span className="block break-words text-[14px] font-semibold">{compactVisionTitle(idea)}</span><span className="text-[11px]" style={{color:"var(--app-a-text-secondary)"}}>{t.draft}</span></span><ChevronRight className="h-4 w-4 opacity-40"/></button>)}</div>}</section>
      <section className="min-w-0">
        {selectedSaved ? <article className="app-a-surface p-4 sm:p-5">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div className="min-w-0 flex-1">
              <h2 className="break-words text-[20px] font-semibold">{compactVisionTitle(selectedSaved.planningContext?.acceptedGoal||selectedSaved.idea)}</h2>
              {selectedSaved.idea!==compactVisionTitle(selectedSaved.idea)?<details className="mt-2 text-[12px]" style={{color:"var(--app-a-text-secondary)"}}><summary className="cursor-pointer font-medium">{t.original}</summary><p className="mt-1 whitespace-pre-wrap break-words leading-relaxed">{selectedSaved.idea}</p></details>:null}
              {focusId===selectedSaved.id?<span className="mt-2 inline-flex items-center gap-1 rounded-full bg-[#34C759]/10 px-2.5 py-1 text-[12px] font-semibold text-[#248A3D]"><Check className="h-3.5 w-3.5"/>{t.current}</span>:null}
            </div>
            <div className="flex flex-wrap gap-2">{selectedSaved.status!=="archived"&&focusId!==selectedSaved.id?<button disabled={!!busy} onClick={()=>void focus(selectedSaved.id)} className="app-a-primary-button px-3 text-[12px]">{t.makeCurrent}</button>:null}<button disabled={!!busy} onClick={()=>void archive(selectedSaved)} className="app-a-secondary-button px-3 text-[12px]">{selectedSaved.status==="archived"?<RotateCcw className="h-4 w-4"/>:<Archive className="h-4 w-4"/>}{selectedSaved.status==="archived"?t.restore:t.archive}</button><button onClick={()=>setConfirm(selectedSaved.id)} className="app-a-secondary-button px-3 text-[12px] text-[#FF3B30]"><Trash2 className="h-4 w-4"/>{t.remove}</button></div>
          </div>
          {selectedSaved.status!=="archived"?<VisionStrategyBuilder key={selectedSaved.id} idea={selectedSaved.idea} language={selectedSaved.language} userId={history.user.uid} initialDocument={selectedSaved} onSaved={doc=>setSaved(all=>[doc,...all.filter(x=>x.id!==doc.id)])}/>:null}
        </article> : selectedDraft ? <article className="app-a-surface p-4 sm:p-5">
          <div className="flex items-start justify-between gap-3"><h2 className="break-words text-[20px] font-semibold">{compactVisionTitle(selectedDraft)}</h2><button onClick={()=>{setManualIdeas(all=>all.filter(x=>x!==selectedDraft));setSelected(null)}} className="h-11 w-11 rounded-full"><X className="mx-auto h-4 w-4"/></button></div>
          <VisionStrategyBuilder key={selectedDraft} idea={selectedDraft} language={language} userId={history.user.uid} onSaved={doc=>{const hadNoActiveVision=saved.every(item=>item.status==="archived");setSaved(all=>[doc,...all.filter(x=>x.id!==doc.id)]);setManualIdeas(all=>all.filter(x=>x!==selectedDraft));setSelected(doc.id);if(!focusId&&hadNoActiveVision)void focus(doc.id)}}/>
        </article> : <div className="app-a-surface flex min-h-[240px] items-center justify-center p-8 text-center"><p>{t.choose}</p></div>}
      </section>
    </div>
    {confirm?<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/45 p-4"><div className="app-a-surface w-full max-w-[420px] p-5"><h2 className="text-[19px] font-semibold">{t.confirm}</h2><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setConfirm(null)} className="app-a-secondary-button px-4">{t.cancel}</button><button onClick={()=>{const item=saved.find(x=>x.id===confirm);if(item)void remove(item)}} className="app-a-secondary-button px-4 text-[#FF3B30]">{t.remove}</button></div></div></div>:null}
  </div>;
}
