export type AppADestination = 'today' | 'inbox' | 'vision' | 'progress' | 'settings';
export type AppALanguage = 'en' | 'sr' | 'tr';
export type AppATheme = 'system' | 'light' | 'dark';

export type AppATimeZoneSetting =
  | { mode: 'automatic' }
  | { mode: 'override'; timeZone: string };

export interface AppAPreferences {
  language: AppALanguage;
  theme: AppATheme;
  timeZoneSetting: AppATimeZoneSetting;
  defaultFocusMinutes: 15 | 25 | 45 | 60;
  aiSuggestionsEnabled: boolean;
}

export type EnergyLevel = 1 | 2 | 3 | 4 | 5;
export type PleasantnessLevel = 1 | 2 | 3 | 4 | 5;
export type AvailableTimeType = '30m' | '1h' | '2h' | '4h' | 'most_day' | 'custom';

export interface AvailableTimeValue {
  type: AvailableTimeType;
  customHours?: number;
  customMinutes?: number;
}

export interface DailyResetData {
  energy?: EnergyLevel;
  pleasantness?: PleasantnessLevel;
  availableTime?: AvailableTimeValue;
  stateNote: string;
  brainDump: string;
}

export const APP_A_TRANSLATIONS = {
  en: {
    // Nav
    today: "Today",
    inbox: "Inbox",
    vision: "Vision",
    progress: "Progress",
    // Descriptions
    todayDesc: "Daily reset, brain dump, AI plan, focus, and evening close.",
    inboxDesc: "New thoughts, items awaiting processing, and deferred tasks.",
    visionDesc: "Vision, goals, projects, and long-term ideas.",
    progressDesc: "Progress toward goals, consistency, and weekly review.",
    destinationPreviewStatus: "Planned for the next product step",
    // Today Daily Reset
    dailyResetTitle: "What’s on your mind today?",
    dailyResetIntro: "Add tasks, ideas, and worries. We’ll suggest a realistic order for today.",
    stateSectionTitle: "How are you feeling?",
    stateSectionSubtitle: "Helps us avoid overloading your day if your energy is low.",
    onboardingTitle: "Let’s make a realistic plan for today",
    onboardingIntro: "Three short steps are enough. You can change everything before saving.",
    onboardingStateHelp: "Helps us avoid overloading your day if your energy is low.",
    onboardingTimeHelp: "Time keeps the plan realistic. We use it as a limit—not a target to fill.",
    onboardingTimeOptional: "You can skip this. The plan may be less precise, and we may ask before adding more work.",
    onboardingMindHelp: "Write or say tasks, ideas, deadlines, and worries. You do not need to organize them.",
    onboardingHowItWorks: "How does this work?",
    onboardingHideHelp: "Hide help",
    onboardingSortTitle: "1. Capture without organizing",
    onboardingSortText: "Write tasks, appointments, notes, worries, or goals in any order. AI separates them.",
    onboardingPrioritizeTitle: "2. Build a realistic order",
    onboardingPrioritizeText: "Energy and mood set the load; AI ranks flexible tasks and estimates time when needed.",
    onboardingControlTitle: "3. You stay in control",
    onboardingControlText: "You review before saving. Fixed commitments stay fixed and notes stay notes until clarified.",
    sectionState: "How are you feeling?",
    sectionTime: "How much time do you have?",
    sectionMind: "What’s on your mind?",
    clearSelection: "Clear",
    // Energy
    energyLabel: "Energy",
    energy1: "Exhausted",
    energy2: "Low",
    energy3: "Okay",
    energy4: "Good",
    energy5: "Energized",
    // Pleasantness
    pleasantnessLabel: "Mood",
    pleasantness1: "Struggling",
    pleasantness2: "Low",
    pleasantness3: "Neutral",
    pleasantness4: "Good",
    pleasantness5: "Great",
    // Time
    time30m: "30 min",
    time1h: "1 h",
    time2h: "2 h",
    time4h: "4 h",
    timeMost: "Most of the day",
    timeCustom: "Custom",
    timeCustomHours: "Hours",
    timeCustomMins: "Minutes",
    timeErrorInvalid: "Please enter a valid time greater than zero.",
    // State Note
    stateNoteLabel: "State note (optional)",
    stateNotePlaceholder: "e.g. slept poorly, headache...",
    stateNoteToggle: "+ Add a quick note about your state",
    // Brain Dump
    brainDumpLabel: "What’s on your mind?",
    brainDumpPlaceholder: "E.g. send report to Ana, buy coffee, worried about 2pm meeting...",
    brainDumpEmptyError: "Please write what is on your mind to create a plan.",
    voicePlaceholder: "Use voice",
    voiceLabel: "Use voice",
    charCount: "characters",
    // Actions
    submitPlan: "Create my plan",
    submitFirstPlan: "Create my plan",
    // Success
    successTitle: "Input Prepared",
    successMsg: "Your daily reset input has been prepared for AI processing. (Temporary development state)",
    backToEdit: "Back to edit",
    // Plan Review
    planRationaleTitle: "Plan Rationale",
    reviewTitle: "Review today’s plan",
    reviewIntro: "Make small adjustments, then save the version you want to follow today.",
    todayPlanTitle: "Your plan for today",
    todayPlanIntro: "Keep the day small. Start with the first focus and return here when you are ready for the next step.",
    completedSummary: "{completed} of {total} completed",
    editTodayPlan: "Adjust plan",
    completionSaveError: "Completion could not be saved. Please try again.",
    requiredTodayLabel: "Planned for today",
    optionalTodayLabel: "Only if capacity remains",
    outsideTodaySummary: "{count} items are safely kept outside today.",
    allTodayComplete: "Today’s planned items are complete.",
    firstFocusTitle: "First focus",
    laterTodayTitle: "Later today",
    ifCapacityRemainsTitle: "If capacity remains",
    ifCapacityRemainsDesc: "Optional tasks to tackle if you have extra time and energy.",
    plannedSummaryText: "Estimated total time: {planned} min",
    plannedWithAvailableText: "Planned: {planned} of {available} min",
    energyDesc1: "Very light",
    energyDesc2: "Light",
    energyDesc3: "Moderate",
    energyDesc4: "Demanding",
    energyDesc5: "Very demanding",
    whyLabel: "Why?",
    checkLabel: "Check",
    keepHere: "Keep here",
    moveToFirstFocus: "Move to First focus",
    moveToLaterToday: "Move to Later today",
    moveToIfCapacityRemains: "Move to If capacity remains",
    moveToThisWeek: "Move to This week",
    moveToLater: "Move to Later",
    removeFromToday: "Remove from today",
    saveAsLongTermIdea: "Save as long-term idea",
    markAsNotAnAction: "Mark as not an action",
    editItem: "Edit",
    itemTitleLabel: "Title",
    itemDescLabel: "Description (optional)",
    itemDurationLabel: "Duration (minutes)",
    saveBtn: "Save",
    cancelBtn: "Cancel",
    emptyTitleError: "Title cannot be empty.",
    invalidDurationError: "Duration must be a positive integer.",
    outsideTodayHeading: "Items outside today",
    thisWeekHeading: "This week",
    laterHeading: "Later",
    longTermIdeasHeading: "Long-term ideas",
    noActionHeading: "No action",
    missingDataExplanation: "Cannot move to today: missing duration or action.",
    optionalInterventionTitle: "Suggested break / intervention (optional)",
    undoBtn: "Undo last change",
    reviewCompleteBtn: "Review complete",
    temporaryReviewConfirmation: "Review complete! Plan saving and task creation will be available in the next update.",
    savingPlan: "Saving plan…",
    planSavedConfirmation: "Your plan is saved for today.",
    planSaveError: "Your plan could not be saved. Please try again.",
    planLoadError: "Your saved plan could not be loaded.",
    firstFocusLimitError: "First focus can contain a maximum of 3 items.",
    emptyBlockText: "No items in this block.",
    actionsMenuLabel: "Actions",
  },
  sr: {
    // Nav
    today: "Danas",
    inbox: "Prijemno",
    vision: "Vizija",
    progress: "Napredak",
    // Descriptions
    todayDesc: "Dnevni reset, rasterećenje uma, AI plan, fokus, i večernji osvrt.",
    inboxDesc: "Nove misli, stavke koje čekaju obradu i odloženi zadaci.",
    visionDesc: "Vizija, ciljevi, projekti i dugoročne ideje.",
    progressDesc: "Napredak ka ciljevima, doslednost i nedeljni pregled.",
    destinationPreviewStatus: "Planirano za sledeći razvojni korak",
    // Today Daily Reset
    dailyResetTitle: "Šta ti je danas na umu?",
    dailyResetIntro: "Napiši obaveze, ideje i brige. Predložićemo realan redosled za danas.",
    stateSectionTitle: "Tvoje trenutno stanje",
    stateSectionSubtitle: "Pomaže nam da ne pretrpamo plan ako si bez snage.",
    onboardingTitle: "Hajde da napravimo realan plan za danas",
    onboardingIntro: "Dovoljna su tri kratka koraka. Sve možete promeniti pre čuvanja.",
    onboardingStateHelp: "Pomaže nam da ne pretrpamo plan ako si bez snage.",
    onboardingTimeHelp: "Vreme sprečava pretrpan plan. Koristimo ga kao granicu, a ne kao prostor koji treba popuniti.",
    onboardingTimeOptional: "Možete preskočiti. Plan može biti manje precizan, pa ćemo možda pitati pre dodavanja novih obaveza.",
    onboardingMindHelp: "Napišite ili izgovorite zadatke, ideje, rokove i brige. Ne morate ih organizovati.",
    onboardingHowItWorks: "Kako ovo radi?",
    onboardingHideHelp: "Sakrij objašnjenja",
    onboardingSortTitle: "1. Unesite sve bez sređivanja",
    onboardingSortText: "Unesite zadatke, termine, beleške, brige ili ciljeve bilo kojim redom. AI ih razdvaja.",
    onboardingPrioritizeTitle: "2. Dobijate realan redosled",
    onboardingPrioritizeText: "Energija i raspoloženje određuju opterećenje; AI rangira fleksibilne zadatke i procenjuje vreme.",
    onboardingControlTitle: "3. Vi zadržavate kontrolu",
    onboardingControlText: "Pregledate sve pre čuvanja. Fiksne obaveze ostaju fiksne, a beleške se prvo razjašnjavaju.",
    sectionState: "Kako se osećaš?",
    sectionTime: "Koliko vremena imate?",
    sectionMind: "Šta ti je na umu?",
    clearSelection: "Obriši",
    // Energy
    energyLabel: "Energija",
    energy1: "Iscrpljeno",
    energy2: "Nisko",
    energy3: "U redu",
    energy4: "Dobro",
    energy5: "Pun snage",
    // Pleasantness
    pleasantnessLabel: "Raspoloženje",
    pleasantness1: "Teško",
    pleasantness2: "Loše",
    pleasantness3: "Neutralno",
    pleasantness4: "Dobro",
    pleasantness5: "Odlično",
    // Time
    time30m: "30 min",
    time1h: "1 h",
    time2h: "2 h",
    time4h: "4 h",
    timeMost: "Veći deo dana",
    timeCustom: "Prilagođeno",
    timeCustomHours: "Sati",
    timeCustomMins: "Minuta",
    timeErrorInvalid: "Unesite validno vreme veće od nule.",
    // State Note
    stateNoteLabel: "Beleška o stanju (opciono)",
    stateNotePlaceholder: "npr. loše sam spavao, boli me glava...",
    stateNoteToggle: "+ Dodaj kratku belešku o stanju",
    // Brain Dump
    brainDumpLabel: "Šta ti je na umu?",
    brainDumpPlaceholder: "Npr. poslati izveštaj Ani, kupiti kafu, brine me sastanak u 14h...",
    brainDumpEmptyError: "Napišite šta vam je na umu da bismo kreirali plan.",
    voicePlaceholder: "Koristi glas",
    voiceLabel: "Koristi glas",
    charCount: "karaktera",
    // Actions
    submitPlan: "Napravi moj plan",
    submitFirstPlan: "Napravi moj plan",
    // Success
    successTitle: "Unos je spreman",
    successMsg: "Vaš dnevni unos je pripremljen za AI obradu. (Privremeno razvojno stanje)",
    backToEdit: "Nazad na izmenu",
    // Plan Review
    planRationaleTitle: "Obrazloženje plana",
    reviewTitle: "Pregledajte današnji plan",
    reviewIntro: "Napravite male izmene, a zatim sačuvajte verziju koju želite da pratite danas.",
    todayPlanTitle: "Vaš plan za danas",
    todayPlanIntro: "Neka dan ostane mali. Počnite od prvog fokusa i vratite se kada budete spremni za sledeći korak.",
    completedSummary: "Završeno {completed} od {total}",
    editTodayPlan: "Prilagodi plan",
    completionSaveError: "Završetak nije sačuvan. Pokušajte ponovo.",
    requiredTodayLabel: "Planirano za danas",
    optionalTodayLabel: "Samo ako ostane kapaciteta",
    outsideTodaySummary: "{count} stavki je bezbedno sačuvano izvan današnjeg plana.",
    allTodayComplete: "Današnje planirane stavke su završene.",
    firstFocusTitle: "Prvi fokus",
    laterTodayTitle: "Kasnije danas",
    ifCapacityRemainsTitle: "Ako ostane kapaciteta",
    ifCapacityRemainsDesc: "Opcioni zadaci ukoliko imate dodatnog vremena i energije.",
    plannedSummaryText: "Procenjeno ukupno vreme: {planned} min",
    plannedWithAvailableText: "Planirano: {planned} od {available} min",
    energyDesc1: "Veoma lako",
    energyDesc2: "Lako",
    energyDesc3: "Umereno",
    energyDesc4: "Zahtevno",
    energyDesc5: "Veoma zahtevno",
    whyLabel: "Zašto?",
    checkLabel: "Proveri",
    keepHere: "Zadrži ovde",
    moveToFirstFocus: "Premesti u Prvi fokus",
    moveToLaterToday: "Premesti u Kasnije danas",
    moveToIfCapacityRemains: "Premesti u Ako ostane kapaciteta",
    moveToThisWeek: "Premesti u Ovu nedelju",
    moveToLater: "Premesti u Kasnije",
    removeFromToday: "Ukloni iz današnjeg plana",
    saveAsLongTermIdea: "Sačuvaj kao dugoročnu ideju",
    markAsNotAnAction: "Označi da nije akcija",
    editItem: "Izmeni",
    itemTitleLabel: "Naslov",
    itemDescLabel: "Opis (opciono)",
    itemDurationLabel: "Trajanje (minuti)",
    saveBtn: "Sačuvaj",
    cancelBtn: "Otkaži",
    emptyTitleError: "Naslov ne može biti prazan.",
    invalidDurationError: "Trajanje mora biti pozitivan ceo broj.",
    outsideTodayHeading: "Stavke izvan današnjeg dana",
    thisWeekHeading: "Ove nedelje",
    laterHeading: "Kasnije",
    longTermIdeasHeading: "Dugoročne ideje",
    noActionHeading: "Nije akcija",
    missingDataExplanation: "Nije moguće premestiti u danas: nedostaje trajanje ili akcija.",
    optionalInterventionTitle: "Predložena pauza / intervencija (opciono)",
    undoBtn: "Poništi poslednju izmenu",
    reviewCompleteBtn: "Pregled završen",
    temporaryReviewConfirmation: "Pregled je završen! Čuvanje plana i kreiranje zadataka biće dostupno u sledećem ažuriranju.",
    savingPlan: "Čuvanje plana…",
    planSavedConfirmation: "Plan za danas je sačuvan.",
    planSaveError: "Plan nije moguće sačuvati. Pokušajte ponovo.",
    planLoadError: "Sačuvani plan nije moguće učitati.",
    firstFocusLimitError: "Prvi fokus može sadržati najviše 3 stavke.",
    emptyBlockText: "Nema stavki u ovom bloku.",
    actionsMenuLabel: "Akcije",
  },
  tr: {
    // Nav
    today: "Bugün",
    inbox: "Gelen Kutusu",
    vision: "Vizyon",
    progress: "İlerleme",
    // Descriptions
    todayDesc: "Günlük sıfırlama, beyin boşaltma, yapay zeka planı, odaklanma ve akşam kapanışı.",
    inboxDesc: "Yeni düşünceler, işlenmeyi bekleyen öğeler ve ertelenen görevler.",
    visionDesc: "Vizyon, hedefler, projeler ve uzun vadeli fikirler.",
    progressDesc: "Hedeflere doğru ilerleme, tutarlılık ve haftalık inceleme.",
    destinationPreviewStatus: "Bir sonraki ürün adımı için planlandı",
    // Today Daily Reset
    dailyResetTitle: "Bugün aklında neler var?",
    dailyResetIntro: "Görevlerini, fikirlerini ve endişelerini yaz. Bugün için gerçekçi bir sıra önerelim.",
    stateSectionTitle: "Nasıl hissediyorsun?",
    stateSectionSubtitle: "Enerjin düşükse gününü fazla doldurmamıza engel olur.",
    onboardingTitle: "Bugün için gerçekçi bir plan yapalım",
    onboardingIntro: "Üç kısa adım yeterli. Kaydetmeden önce her şeyi değiştirebilirsiniz.",
    onboardingStateHelp: "Enerjin düşükse gününü fazla doldurmamıza engel olur.",
    onboardingTimeHelp: "Süre planı gerçekçi tutar. Onu doldurulacak bir hedef değil, sınır olarak kullanırız.",
    onboardingTimeOptional: "Bu adımı atlayabilirsiniz. Plan daha az kesin olabilir ve yeni işler eklemeden önce size sorabiliriz.",
    onboardingMindHelp: "Görevleri, fikirleri, son tarihleri ve endişeleri yazın veya söyleyin. Düzenlemeniz gerekmez.",
    onboardingHowItWorks: "Bu nasıl çalışır?",
    onboardingHideHelp: "Yardımı gizle",
    onboardingSortTitle: "1. Düzenlemeden her şeyi ekleyin",
    onboardingSortText: "Görevleri, randevuları, notları, endişeleri veya hedefleri istediğiniz sırada yazın. Yapay zekâ bunları ayırır.",
    onboardingPrioritizeTitle: "2. Gerçekçi bir sıra oluşturun",
    onboardingPrioritizeText: "Enerji ve ruh hali yükü belirler; yapay zekâ esnek görevleri sıralar ve gerektiğinde süreyi tahmin eder.",
    onboardingControlTitle: "3. Kontrol sizde kalır",
    onboardingControlText: "Kaydetmeden önce her şeyi incelersiniz. Sabit yükümlülükler sabit kalır, notlar önce açıklığa kavuşturulur.",
    sectionState: "Nasıl hissediyorsun?",
    sectionTime: "Ne kadar zamanınız var?",
    sectionMind: "Aklında ne var?",
    clearSelection: "Temizle",
    // Energy
    energyLabel: "Enerji",
    energy1: "Tükenmiş",
    energy2: "Düşük",
    energy3: "İyi",
    energy4: "Yüksek",
    energy5: "Dolu",
    // Pleasantness
    pleasantnessLabel: "Ruh hali",
    pleasantness1: "Zorlanıyor",
    pleasantness2: "Kötü",
    pleasantness3: "Nötr",
    pleasantness4: "İyi",
    pleasantness5: "Harika",
    // Time
    time30m: "30 dk",
    time1h: "1 sa",
    time2h: "2 sa",
    time4h: "4 sa",
    timeMost: "Günün çoğu",
    timeCustom: "Özel",
    timeCustomHours: "Saat",
    timeCustomMins: "Dakika",
    timeErrorInvalid: "Lütfen sıfırdan büyük geçerli bir süre girin.",
    // State Note
    stateNoteLabel: "Durum notu (isteğe bağlı)",
    stateNotePlaceholder: "örn. kötü uyudum, başım ağrıyor...",
    stateNoteToggle: "+ Durumun hakkında kısa bir not ekle",
    // Brain Dump
    brainDumpLabel: "Aklında ne var?",
    brainDumpPlaceholder: "Örn. Ana’ya raporu gönder, kahve al, saat 14’teki toplantı beni endişelendiriyor...",
    brainDumpEmptyError: "Bir plan oluşturmak için lütfen aklınızdakileri yazın.",
    voicePlaceholder: "Sesle yaz",
    voiceLabel: "Sesle yaz",
    charCount: "karakter",
    // Actions
    submitPlan: "Planımı oluştur",
    submitFirstPlan: "Planımı oluştur",
    // Success
    successTitle: "Girdi Hazırlandı",
    successMsg: "Günlük sıfırlama girdiniz AI işleme için hazırlandı. (Geçici geliştirme durumu)",
    backToEdit: "Düzenlemeye dön",
    // Plan Review
    planRationaleTitle: "Plan Gerekçesi",
    reviewTitle: "Bugünkü planı gözden geçirin",
    reviewIntro: "Küçük düzenlemeler yapın, ardından bugün uygulamak istediğiniz sürümü kaydedin.",
    todayPlanTitle: "Bugünkü planınız",
    todayPlanIntro: "Günü küçük tutun. İlk odakla başlayın ve bir sonraki adıma hazır olduğunuzda buraya dönün.",
    completedSummary: "{total} öğeden {completed} tamamlandı",
    editTodayPlan: "Planı düzenle",
    completionSaveError: "Tamamlama kaydedilemedi. Lütfen tekrar deneyin.",
    requiredTodayLabel: "Bugün için planlananlar",
    optionalTodayLabel: "Yalnızca kapasite kalırsa",
    outsideTodaySummary: "{count} öğe bugünün dışında güvenle saklandı.",
    allTodayComplete: "Bugün planlanan öğeler tamamlandı.",
    firstFocusTitle: "İlk odak",
    laterTodayTitle: "Bugün daha sonra",
    ifCapacityRemainsTitle: "Kapasite kalırsa",
    ifCapacityRemainsDesc: "Ekstra zamanınız ve enerjiniz olursa yapılacak isteğe bağlı görevler.",
    plannedSummaryText: "Tahmini toplam süre: {planned} dk",
    plannedWithAvailableText: "Planlanan: {available} dk içinden {planned} dk",
    energyDesc1: "Çok hafif",
    energyDesc2: "Hafif",
    energyDesc3: "Orta",
    energyDesc4: "Zorlu",
    energyDesc5: "Çok zorlu",
    whyLabel: "Neden?",
    checkLabel: "Kontrol et",
    keepHere: "Burada tut",
    moveToFirstFocus: "İlk odağa taşı",
    moveToLaterToday: "Bugün daha sonraya taşı",
    moveToIfCapacityRemains: "Kapasite kalırsaya taşı",
    moveToThisWeek: "Bu haftaya taşı",
    moveToLater: "Daha sonraya taşı",
    removeFromToday: "Bugünün planından kaldır",
    saveAsLongTermIdea: "Uzun vadeli fikir olarak kaydet",
    markAsNotAnAction: "Eylem değil olarak işaretle",
    editItem: "Düzenle",
    itemTitleLabel: "Başlık",
    itemDescLabel: "Açıklama (isteğe bağlı)",
    itemDurationLabel: "Süre (dakika)",
    saveBtn: "Kaydet",
    cancelBtn: "İptal",
    emptyTitleError: "Başlık boş olamaz.",
    invalidDurationError: "Süre pozitif bir tam sayı olmalıdır.",
    outsideTodayHeading: "Bugün dışındaki öğeler",
    thisWeekHeading: "Bu hafta",
    laterHeading: "Daha sonra",
    longTermIdeasHeading: "Uzun vadeli fikirler",
    noActionHeading: "Eylem yok",
    missingDataExplanation: "Bugüne taşınamıyor: eksik süre veya eylem.",
    optionalInterventionTitle: "Önerilen mola / müdahale (isteğe bağlı)",
    undoBtn: "Son değişikliği geri al",
    reviewCompleteBtn: "İnceleme tamamlandı",
    temporaryReviewConfirmation: "İnceleme tamamlandı! Plan kaydetme ve görev oluşturma bir sonraki güncellemede mevcut olacaktır.",
    savingPlan: "Plan kaydediliyor…",
    planSavedConfirmation: "Bugünkü planınız kaydedildi.",
    planSaveError: "Planınız kaydedilemedi. Lütfen tekrar deneyin.",
    planLoadError: "Kaydedilmiş planınız yüklenemedi.",
    firstFocusLimitError: "İlk odak en fazla 3 öğe içerebilir.",
    emptyBlockText: "Bu blokta öğe yok.",
    actionsMenuLabel: "Eylemler",
  }
} as const;
