export type AppADestination = 'today' | 'inbox' | 'vision' | 'progress' | 'settings';
export type AppALanguage = 'en' | 'sr' | 'tr';
export type AppATheme = 'system' | 'light' | 'dark';

export type AppATimeZoneSetting =
  | { mode: 'automatic' }
  | { mode: 'override'; timeZone: string };

export interface AppAPreferences {
  language: AppALanguage;
  theme: AppATheme;
  timeZoneSetting: AppATimeZoneSetting;
  defaultFocusMinutes: 15 | 25 | 45 | 60;
  aiSuggestionsEnabled: boolean;
}

export type EnergyLevel = 1 | 2 | 3 | 4 | 5;
export type PleasantnessLevel = 1 | 2 | 3 | 4 | 5;
export type AvailableTimeType = '30m' | '1h' | '2h' | '4h' | 'most_day' | 'custom';

export interface AvailableTimeValue {
  type: AvailableTimeType;
  customHours?: number;
  customMinutes?: number;
}

export interface DailyResetData {
  energy?: EnergyLevel;
  pleasantness?: PleasantnessLevel;
  availableTime?: AvailableTimeValue;
  stateNote: string;
  brainDump: string;
}

export const APP_A_TRANSLATIONS = {
  en: {
    // Nav
    today: "Today",
    inbox: "Inbox",
    vision: "Vision",
    progress: "Progress",
    // Descriptions
    todayDesc: "Daily reset, brain dump, AI plan, focus, and evening close.",
    inboxDesc: "New thoughts, items awaiting processing, and deferred tasks.",
    visionDesc: "Vision, goals, projects, and long-term ideas.",
    progressDesc: "Progress toward goals, consistency, and weekly review.",
    destinationPreviewStatus: "Planned for the next product step",
    // Today Daily Reset
    dailyResetTitle: "Daily Reset",
    dailyResetIntro: "Empty your mind and let AI help you create a realistic plan for the day.",
    sectionState: "How are you right now?",
    sectionTime: "How much time do you have?",
    sectionMind: "What’s on your mind?",
    clearSelection: "Clear",
    // Energy
    energyLabel: "Current energy",
    energy1: "Very low",
    energy2: "Low",
    energy3: "Medium",
    energy4: "High",
    energy5: "Very high",
    // Pleasantness
    pleasantnessLabel: "Current pleasantness",
    pleasantness1: "Very unpleasant",
    pleasantness2: "Unpleasant",
    pleasantness3: "Neutral",
    pleasantness4: "Pleasant",
    pleasantness5: "Very pleasant",
    // Time
    time30m: "30 min",
    time1h: "1 h",
    time2h: "2 h",
    time4h: "4 h",
    timeMost: "Most of the day",
    timeCustom: "Custom",
    timeCustomHours: "Hours",
    timeCustomMins: "Minutes",
    timeErrorInvalid: "Please enter a valid time greater than zero.",
    // State Note
    stateNoteLabel: "State note (optional)",
    stateNotePlaceholder: "e.g., I didn't sleep well...",
    // Brain Dump
    brainDumpLabel: "Brain dump",
    brainDumpPlaceholder: "Write whatever is on your mind. Tasks, ideas, worries...",
    brainDumpEmptyError: "Please write what is on your mind to create a plan.",
    voicePlaceholder: "Coming next",
    voiceLabel: "Use voice (Coming next)",
    charCount: "characters",
    // Actions
    submitPlan: "Create my plan",
    // Success
    successTitle: "Input Prepared",
    successMsg: "Your daily reset input has been prepared for AI processing. (Temporary development state)",
    backToEdit: "Back to edit",
    // Plan Review
    planRationaleTitle: "Plan Rationale",
    reviewTitle: "Review today’s plan",
    reviewIntro: "Make small adjustments, then save the version you want to follow today.",
    todayPlanTitle: "Your plan for today",
    todayPlanIntro: "Keep the day small. Start with the first focus and return here when you are ready for the next step.",
    completedSummary: "{completed} of {total} completed",
    editTodayPlan: "Adjust plan",
    completionSaveError: "Completion could not be saved. Please try again.",
    requiredTodayLabel: "Planned for today",
    optionalTodayLabel: "Only if capacity remains",
    outsideTodaySummary: "{count} items are safely kept outside today.",
    allTodayComplete: "Today’s planned items are complete.",
    firstFocusTitle: "First focus",
    laterTodayTitle: "Later today",
    ifCapacityRemainsTitle: "If capacity remains",
    ifCapacityRemainsDesc: "Optional tasks to tackle if you have extra time and energy.",
    plannedSummaryText: "Estimated total time: {planned} min",
    plannedWithAvailableText: "Planned: {planned} of {available} min",
    energyDesc1: "Very light",
    energyDesc2: "Light",
    energyDesc3: "Moderate",
    energyDesc4: "Demanding",
    energyDesc5: "Very demanding",
    whyLabel: "Why?",
    checkLabel: "Check",
    keepHere: "Keep here",
    moveToFirstFocus: "Move to First focus",
    moveToLaterToday: "Move to Later today",
    moveToIfCapacityRemains: "Move to If capacity remains",
    moveToThisWeek: "Move to This week",
    moveToLater: "Move to Later",
    saveAsLongTermIdea: "Save as long-term idea",
    markAsNotAnAction: "Mark as not an action",
    editItem: "Edit",
    itemTitleLabel: "Title",
    itemDescLabel: "Description (optional)",
    itemDurationLabel: "Duration (minutes)",
    saveBtn: "Save",
    cancelBtn: "Cancel",
    emptyTitleError: "Title cannot be empty.",
    invalidDurationError: "Duration must be a positive integer.",
    outsideTodayHeading: "Items outside today",
    thisWeekHeading: "This week",
    laterHeading: "Later",
    longTermIdeasHeading: "Long-term ideas",
    noActionHeading: "No action",
    missingDataExplanation: "Cannot move to today: missing duration or action.",
    optionalInterventionTitle: "Suggested break / intervention (optional)",
    undoBtn: "Undo last change",
    reviewCompleteBtn: "Review complete",
    temporaryReviewConfirmation: "Review complete! Plan saving and task creation will be available in the next update.",
    savingPlan: "Saving plan…",
    planSavedConfirmation: "Your plan is saved for today.",
    planSaveError: "Your plan could not be saved. Please try again.",
    planLoadError: "Your saved plan could not be loaded.",
    firstFocusLimitError: "First focus can contain a maximum of 3 items.",
    emptyBlockText: "No items in this block.",
    actionsMenuLabel: "Actions",
  },
  sr: {
    // Nav
    today: "Danas",
    inbox: "Prijemno",
    vision: "Vizija",
    progress: "Napredak",
    // Descriptions
    todayDesc: "Dnevni reset, rasterećenje uma, AI plan, fokus, i večernji osvrt.",
    inboxDesc: "Nove misli, stavke koje čekaju obradu i odloženi zadaci.",
    visionDesc: "Vizija, ciljevi, projekti i dugoročne ideje.",
    progressDesc: "Napredak ka ciljevima, doslednost i nedeljni pregled.",
    destinationPreviewStatus: "Planirano za sledeći razvojni korak",
    // Today Daily Reset
    dailyResetTitle: "Dnevni Reset",
    dailyResetIntro: "Oslobodite um i dozvolite veštačkoj inteligenciji da vam pomogne u kreiranju realnog plana za danas.",
    sectionState: "Kako ste trenutno?",
    sectionTime: "Koliko vremena imate?",
    sectionMind: "Šta vam je na umu?",
    clearSelection: "Obriši",
    // Energy
    energyLabel: "Trenutna energija",
    energy1: "Veoma niska",
    energy2: "Niska",
    energy3: "Srednja",
    energy4: "Visoka",
    energy5: "Veoma visoka",
    // Pleasantness
    pleasantnessLabel: "Trenutno raspoloženje (prijatnost)",
    pleasantness1: "Veoma neprijatno",
    pleasantness2: "Neprijatno",
    pleasantness3: "Neutralno",
    pleasantness4: "Prijatno",
    pleasantness5: "Veoma prijatno",
    // Time
    time30m: "30 min",
    time1h: "1 h",
    time2h: "2 h",
    time4h: "4 h",
    timeMost: "Veći deo dana",
    timeCustom: "Prilagođeno",
    timeCustomHours: "Sati",
    timeCustomMins: "Minuta",
    timeErrorInvalid: "Unesite validno vreme veće od nule.",
    // State Note
    stateNoteLabel: "Beleška o stanju (opciono)",
    stateNotePlaceholder: "npr. Nisam dobro spavao/la...",
    // Brain Dump
    brainDumpLabel: "Misli (Brain dump)",
    brainDumpPlaceholder: "Napišite sve što vam je na umu. Zadaci, ideje, brige...",
    brainDumpEmptyError: "Napišite šta vam je na umu da bismo kreirali plan.",
    voicePlaceholder: "Uskoro",
    voiceLabel: "Koristi glas (Uskoro)",
    charCount: "karaktera",
    // Actions
    submitPlan: "Kreiraj moj plan",
    // Success
    successTitle: "Unos je spreman",
    successMsg: "Vaš dnevni unos je pripremljen za AI obradu. (Privremeno razvojno stanje)",
    backToEdit: "Nazad na izmenu",
    // Plan Review
    planRationaleTitle: "Obrazloženje plana",
    reviewTitle: "Pregledajte današnji plan",
    reviewIntro: "Napravite male izmene, a zatim sačuvajte verziju koju želite da pratite danas.",
    todayPlanTitle: "Vaš plan za danas",
    todayPlanIntro: "Neka dan ostane mali. Počnite od prvog fokusa i vratite se kada budete spremni za sledeći korak.",
    completedSummary: "Završeno {completed} od {total}",
    editTodayPlan: "Prilagodi plan",
    completionSaveError: "Završetak nije sačuvan. Pokušajte ponovo.",
    requiredTodayLabel: "Planirano za danas",
    optionalTodayLabel: "Samo ako ostane kapaciteta",
    outsideTodaySummary: "{count} stavki je bezbedno sačuvano izvan današnjeg plana.",
    allTodayComplete: "Današnje planirane stavke su završene.",
    firstFocusTitle: "Prvi fokus",
    laterTodayTitle: "Kasnije danas",
    ifCapacityRemainsTitle: "Ako ostane kapaciteta",
    ifCapacityRemainsDesc: "Opcioni zadaci ukoliko imate dodatnog vremena i energije.",
    plannedSummaryText: "Procenjeno ukupno vreme: {planned} min",
    plannedWithAvailableText: "Planirano: {planned} od {available} min",
    energyDesc1: "Veoma lako",
    energyDesc2: "Lako",
    energyDesc3: "Umereno",
    energyDesc4: "Zahtevno",
    energyDesc5: "Veoma zahtevno",
    whyLabel: "Zašto?",
    checkLabel: "Proveri",
    keepHere: "Zadrži ovde",
    moveToFirstFocus: "Premesti u Prvi fokus",
    moveToLaterToday: "Premesti u Kasnije danas",
    moveToIfCapacityRemains: "Premesti u Ako ostane kapaciteta",
    moveToThisWeek: "Premesti u Ovu nedelju",
    moveToLater: "Premesti u Kasnije",
    saveAsLongTermIdea: "Sačuvaj kao dugoročnu ideju",
    markAsNotAnAction: "Označi da nije akcija",
    editItem: "Izmeni",
    itemTitleLabel: "Naslov",
    itemDescLabel: "Opis (opciono)",
    itemDurationLabel: "Trajanje (minuti)",
    saveBtn: "Sačuvaj",
    cancelBtn: "Otkaži",
    emptyTitleError: "Naslov ne može biti prazan.",
    invalidDurationError: "Trajanje mora biti pozitivan ceo broj.",
    outsideTodayHeading: "Stavke izvan današnjeg dana",
    thisWeekHeading: "Ove nedelje",
    laterHeading: "Kasnije",
    longTermIdeasHeading: "Dugoročne ideje",
    noActionHeading: "Nije akcija",
    missingDataExplanation: "Nije moguće premestiti u danas: nedostaje trajanje ili akcija.",
    optionalInterventionTitle: "Predložena pauza / intervencija (opciono)",
    undoBtn: "Poništi poslednju izmenu",
    reviewCompleteBtn: "Pregled završen",
    temporaryReviewConfirmation: "Pregled je završen! Čuvanje plana i kreiranje zadataka biće dostupno u sledećem ažuriranju.",
    savingPlan: "Čuvanje plana…",
    planSavedConfirmation: "Plan za danas je sačuvan.",
    planSaveError: "Plan nije moguće sačuvati. Pokušajte ponovo.",
    planLoadError: "Sačuvani plan nije moguće učitati.",
    firstFocusLimitError: "Prvi fokus može sadržati najviše 3 stavke.",
    emptyBlockText: "Nema stavki u ovom bloku.",
    actionsMenuLabel: "Akcije",
  },
  tr: {
    // Nav
    today: "Bugün",
    inbox: "Gelen Kutusu",
    vision: "Vizyon",
    progress: "İlerleme",
    // Descriptions
    todayDesc: "Günlük sıfırlama, beyin boşaltma, yapay zeka planı, odaklanma ve akşam kapanışı.",
    inboxDesc: "Yeni düşünceler, işlenmeyi bekleyen öğeler ve ertelenen görevler.",
    visionDesc: "Vizyon, hedefler, projeler ve uzun vadeli fikirler.",
    progressDesc: "Hedeflere doğru ilerleme, tutarlılık ve haftalık inceleme.",
    destinationPreviewStatus: "Bir sonraki ürün adımı için planlandı",
    // Today Daily Reset
    dailyResetTitle: "Günlük Sıfırlama",
    dailyResetIntro: "Zihninizi boşaltın ve yapay zekanın gün için gerçekçi bir plan oluşturmanıza yardımcı olmasına izin verin.",
    sectionState: "Şu an nasılsınız?",
    sectionTime: "Ne kadar zamanınız var?",
    sectionMind: "Aklınızda ne var?",
    clearSelection: "Temizle",
    // Energy
    energyLabel: "Mevcut enerji",
    energy1: "Çok düşük",
    energy2: "Düşük",
    energy3: "Orta",
    energy4: "Yüksek",
    energy5: "Çok yüksek",
    // Pleasantness
    pleasantnessLabel: "Mevcut hoşluk",
    pleasantness1: "Çok nahoş",
    pleasantness2: "Nahoş",
    pleasantness3: "Nötr",
    pleasantness4: "Hoş",
    pleasantness5: "Çok hoş",
    // Time
    time30m: "30 dk",
    time1h: "1 sa",
    time2h: "2 sa",
    time4h: "4 sa",
    timeMost: "Günün çoğu",
    timeCustom: "Özel",
    timeCustomHours: "Saat",
    timeCustomMins: "Dakika",
    timeErrorInvalid: "Lütfen sıfırdan büyük geçerli bir süre girin.",
    // State Note
    stateNoteLabel: "Durum notu (isteğe bağlı)",
    stateNotePlaceholder: "örn. İyi uyuyamadım...",
    // Brain Dump
    brainDumpLabel: "Beyin boşaltma",
    brainDumpPlaceholder: "Aklınızdan geçenleri yazın. Görevler, fikirler, endişeler...",
    brainDumpEmptyError: "Bir plan oluşturmak için lütfen aklınızdakileri yazın.",
    voicePlaceholder: "Yakında",
    voiceLabel: "Ses kullan (Yakında)",
    charCount: "karakter",
    // Actions
    submitPlan: "Planımı oluştur",
    // Success
    successTitle: "Girdi Hazırlandı",
    successMsg: "Günlük sıfırlama girdiniz AI işleme için hazırlandı. (Geçici geliştirme durumu)",
    backToEdit: "Düzenlemeye dön",
    // Plan Review
    planRationaleTitle: "Plan Gerekçesi",
    reviewTitle: "Bugünkü planı gözden geçirin",
    reviewIntro: "Küçük düzenlemeler yapın, ardından bugün uygulamak istediğiniz sürümü kaydedin.",
    todayPlanTitle: "Bugünkü planınız",
    todayPlanIntro: "Günü küçük tutun. İlk odakla başlayın ve bir sonraki adıma hazır olduğunuzda buraya dönün.",
    completedSummary: "{total} öğeden {completed} tamamlandı",
    editTodayPlan: "Planı düzenle",
    completionSaveError: "Tamamlama kaydedilemedi. Lütfen tekrar deneyin.",
    requiredTodayLabel: "Bugün için planlananlar",
    optionalTodayLabel: "Yalnızca kapasite kalırsa",
    outsideTodaySummary: "{count} öğe bugünün dışında güvenle saklandı.",
    allTodayComplete: "Bugün planlanan öğeler tamamlandı.",
    firstFocusTitle: "İlk odak",
    laterTodayTitle: "Bugün daha sonra",
    ifCapacityRemainsTitle: "Kapasite kalırsa",
    ifCapacityRemainsDesc: "Ekstra zamanınız ve enerjiniz olursa yapılacak isteğe bağlı görevler.",
    plannedSummaryText: "Tahmini toplam süre: {planned} dk",
    plannedWithAvailableText: "Planlanan: {available} dk içinden {planned} dk",
    energyDesc1: "Çok hafif",
    energyDesc2: "Hafif",
    energyDesc3: "Orta",
    energyDesc4: "Zorlu",
    energyDesc5: "Çok zorlu",
    whyLabel: "Neden?",
    checkLabel: "Kontrol et",
    keepHere: "Burada tut",
    moveToFirstFocus: "İlk odağa taşı",
    moveToLaterToday: "Bugün daha sonraya taşı",
    moveToIfCapacityRemains: "Kapasite kalırsaya taşı",
    moveToThisWeek: "Bu haftaya taşı",
    moveToLater: "Daha sonraya taşı",
    saveAsLongTermIdea: "Uzun vadeli fikir olarak kaydet",
    markAsNotAnAction: "Eylem değil olarak işaretle",
    editItem: "Düzenle",
    itemTitleLabel: "Başlık",
    itemDescLabel: "Açıklama (isteğe bağlı)",
    itemDurationLabel: "Süre (dakika)",
    saveBtn: "Kaydet",
    cancelBtn: "İptal",
    emptyTitleError: "Başlık boş olamaz.",
    invalidDurationError: "Süre pozitif bir tam sayı olmalıdır.",
    outsideTodayHeading: "Bugün dışındaki öğeler",
    thisWeekHeading: "Bu hafta",
    laterHeading: "Daha sonra",
    longTermIdeasHeading: "Uzun vadeli fikirler",
    noActionHeading: "Eylem yok",
    missingDataExplanation: "Bugüne taşınamıyor: eksik süre veya eylem.",
    optionalInterventionTitle: "Önerilen mola / müdahale (isteğe bağlı)",
    undoBtn: "Son değişikliği geri al",
    reviewCompleteBtn: "İnceleme tamamlandı",
    temporaryReviewConfirmation: "İnceleme tamamlandı! Plan kaydetme ve görev oluşturma bir sonraki güncellemede mevcut olacaktır.",
    savingPlan: "Plan kaydediliyor…",
    planSavedConfirmation: "Bugünkü planınız kaydedildi.",
    planSaveError: "Planınız kaydedilemedi. Lütfen tekrar deneyin.",
    planLoadError: "Kaydedilmiş planınız yüklenemedi.",
    firstFocusLimitError: "İlk odak en fazla 3 öğe içerebilir.",
    emptyBlockText: "Bu blokta öğe yok.",
    actionsMenuLabel: "Eylemler",
  }
} as const;
